### ISSUE TITLE
Getting strange pulses each 2 seconds

### ISSUE THREAD

**Issue by bestware** [oxullo/Arduino-MAX30100#32] opened 2017-11-18 20:50 UTC
### Description of the issue
Using the debug-prog + rolling graph can see strange pulses occuring exactly every 2 seconds! 
(Very high peak followed by some negative samples) - then ok till next peak.

No idea where  this peaks come from (visible in Serial monitor as well) 
![2sec_pulses](https://user-images.githubusercontent.com/20655970/32984634-7b4b318e-ccaa-11e7-9e4b-3ac14da5352f.JPG)

### Output from MAX30100_Tester example
Initializing MAX30100..Success
Enabling HR/SPO2 mode..done.
Configuring LEDs biases to 50mA..done.
Initializing MAX30100..Success
Enabling HR/SPO2 mode..done.
Configuring LEDs biases to 50mA..done.
Lowering the current to 7.6mA..done.
Shutting down..done.
Resuming normal operation..done.
Sampling die temperature..done, temp=38.56C
All test pass. Press any key to go into sampling loop mode

### Details of my setup
* Arduino hardware:
Mega 2560 (different hardware tested - same result)
* MAX30100 breakout:
RCWL-0530
* Arduino framework version:
* MAX30100 library version:
1.10 (newest)

**Comment by oxullo** [comment] 2017-11-19 18:09
@bestware thanks for pointing it out. It's surely a regression caused by b2fa5675 and it could be also the reason for a bunch of reports regarding the unreliable bpm count.

**Comment by oxullo** [comment] 2017-11-19 18:17
@bestware could you give a try to the branch https://github.com/oxullo/Arduino-MAX30100/tree/issues/%2332/workaround ?

**Comment by bestware** [comment] 2017-11-19 19:36
Great - works like a charm!
Thank you for quick reply.
![hr_ok](https://user-images.githubusercontent.com/20655970/32994522-f71cd6aa-cd68-11e7-97a0-98b148b1f9a5.JPG)

**Comment by oxullo** [comment] 2017-11-19 23:03
It looks to me that it's a bug of the MAX30100. The flag to start the temperature readout must be set on register 0x6, which controls the operating mode of the sensor and I guess that setting this register triggers a momentary shutdown of the LED drivers, injecting a transient in the samples series and temporarily blinding the bpm counter.
In the new design, MAX30102 the temperature enable flag has been silently moved to a different register..

I fixed it by removing the temperature poller from the PulseOximeter class. The change is in master and it will be released soon.

**Closed by oxullo** 2017-11-19 23:03 UTC
