### ISSUE TITLE
Could not convery from void to bool

### ISSUE THREAD

**Issue by danelpo** [oxullo/Arduino-MAX30100#55] opened 2019-01-14 16:27 UTC
### Troubleshooting checklist

- [x] I read the README (on master) thoroughly
- [x] I ran the MAX30100_Tester and I'm going to paste the output down below
- [x] I filled in all the details of my setup down below

### Description of the issue
When I put the example code in, it highlights the line where it checked if pox has begun:
if (!pox.begin()) {
        Serial.println("FAILED");
        for(;;);
    } else {
        Serial.println("SUCCESS");
    }
and the message is:

Arduino: 1.8.8 (Windows Store 1.8.19.0) (Windows 10), Board: "Arduino/Genuino Uno"

MAX30100_Minimal:48:19: error: could not convert 'pox.PulseOximeter::begin((PulseOximeterDebuggingMode)0u)' from 'void' to 'bool'

     if (!pox.begin()) {

                   ^

MAX30100_Minimal:48:20: error: in argument to unary !

     if (!pox.begin()) {

                    ^

Multiple libraries were found for "MAX30100_PulseOximeter.h"
 Used: C:\Users\Documents\Arduino\libraries\MAX30100
 Not used: C:\Users\danel\Documents\Arduino\libraries\Arduino-MAX30100-master
 Not used: C:\Users\danel\Documents\Arduino\libraries\Arduino-MAX30100-master
 Not used: C:\Users\danel\Documents\Arduino\libraries\Arduino-MAX30100-master
 Not used: C:\Users\danel\Documents\Arduino\libraries\Arduino-MAX30100-master
exit status 1
could not convert 'pox.PulseOximeter::begin((PulseOximeterDebuggingMode)0u)' from 'void' to 'bool'

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

If I were to comment that part out it will not even turn the LED on and the HR would be 0.

### Details of my setup
I have the MAX30100 plugged into 3.3v (I also tried 5) and ground, pin SCL connected intoA5, pin SDA into A4 and INT into 2.

**Comment by Jivansha** [comment] 2019-01-14 18:29
Hey! Please use 4.7k pull up resistors in parallel with SCL and SDA to avoid any I2C errors later. Also, there shouldn't be a problem if you have included all the libraries of MAX30100 and initialised the sensor properly before using pox.begin() command. Try looking into the examples of this library and if the problem persists please share the complete code.

**Comment by oxullo** [comment] 2019-02-04 08:15
@danelpo as @Jivansha suggested, it might be a missing include. I trust that you installed the library using the library manager and loaded the examples using the arduino's menu under File->Examples.

I'm closing the issue since I cannot reproduce it.

**Closed as completed by oxullo** 2019-02-04 08:15 UTC
